title: AEK Analiz
description: Tarih ve Finans Analiz Portalı
baseurl: "/TarihBlogu"
url: "https://evrnkir.github.io"

# Tema ayarını sildik, böylece main.css aktif olacak
plugins:
  - jekyll-feed

# Dil ayarı (isteğe bağlı)
languages: ["tr", "en"]