title: AEK Analiz
email: ademevrenkir@gmail.com
description: Tarih, Teknoloji ve Stratejinin Kesişim Noktası
baseurl: "/TarihBlogu"
url: "https://evrnkir.github.io"

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown
  - projects.md
  - reading-list.md