title: AEK Analiz
description: Tarih ve Finans Analiz Portalı
baseurl: "/TarihBlogu"
url: "https://evrnkir.github.io"

# BU SATIR ÇOK ÖNEMLİ! Sitenin iskeletini bu sağlar.
theme: minima

plugins:
  - jekyll-feed

languages: ["tr", "en"]