remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
title: AEK Analiz
description: Tarih ve Finans Analiz PortalÄ±
baseurl: "/TarihBlogu"
url: "https://evrnkir.github.io"