# Site Bilgileri
title: Tarih ve Analiz Blogu
email: ademevrenkir@gmail.com
description: >-
  Tarihi olayların ekonomi, siyaset ve bilim üzerindeki derinlemesine
  analizlerini içeren makaleler.

# URL Ayarları
url: "https://evrnkir.github.io"
baseurl: "/TarihBlogu"

# Tema ve Stil
theme: minima

# Eklentiler (Hata veren kısım burasıydı, tirelerin hizasına dikkat!)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Dosya İstisnaları
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/

# Sayfa Ayarları
header_pages:
  - about.markdown
  - projects.md
  - reading-list.md
languages: ["tr", "en"]
# Sass Ayarları
sass:
  style: compressed
  load_paths:
    - _sass
 market_symbols: '[{"proName":"BIST:XU100","title":"BIST 100"},{"proName":"FOREXCOM:SPX3500","title":"S&P 500"},{"proName":"FX_IDC:XAUUSD","title":"Altın"},{"proName":"FX:USDTRY","title":"USD/TRY"},{"proName":"BITSTAMP:BTCUSD","title":"Bitcoin"}]'   